### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by kutyel** [kutyel/babel-plugin-remove-test-ids#3]
I'd like to add a link to the slides of the mentioned talk by @ForbesLindesay (when they are published) and embed inside the README.md file the video of the talk, I think is a great task for beginners 😉

**Comment by elias-garcia** [comment]
I can take this! 😄

**Comment by Nix07** [comment]
@kutyel Can I take up this issue. I am new to open source world and I think this would be a great way for me to start the HACKTOBERFEST!

**Comment by kutyel** [comment]
Sure! go ahead and give it a try! You might have to wait until the speaker uploads both the slides and the video of the talk of React Alicante 2017, thats the only dependency 😉

**Comment by Nix07** [comment]
Where is he going to upload these resources, on github?

**Comment by kutyel** [comment]
I don't think so, you can speak to the organisers of the conf, @nacmartin and @vicqr (on Twitter), is all I can help you 😄

**Comment by Nix07** [comment]
I got the slides from @ForbesLindesay. Check it out - https://github.com/ForbesLindesay/end-to-end-testing-react-applications/blob/master/end%20to%20end%20testing%20react%20applications.pdf
Regarding the video, I have mailed both the organisers with this issue. Still waiting for the reply from them.

**Comment by kutyel** [comment]
Awesome! You are 1 step closer to fixing this issue, thanks for your work so far! ❤️

**Comment by Nix07** [comment]
I just got a reply from Victoria (@vicqr).  The videos are expected to be online in a couple of weeks, as soon as the company in charge finishes editing/preparing them. They will post them as soon as, they get it!
In the meantime, we can add the link to the slides in README file.

**Comment by kutyel** [comment]
Sure! why not 👍

**Comment by nacmartin** [comment]
Yes, so about the videos, there is a company doing the postprod, adjusting volumes, cutting, and so on. Then they will send us a hard drive with them, we upload them. All of this takes time, there are several steps involved, and so on.

**Comment by kutyel** [comment]
Sure! No problem, we will add the embed video once it is published, thanks! 🎉

**Comment by kutyel** [comment]
BTW you can both support the plugin by giving it a ⭐️ on github! 😜
