### ISSUE TITLE
Compilation times much slower with this plugin

### ISSUE THREAD

**Issue by Floriferous** [kutyel/babel-plugin-remove-test-ids#6]
I don't know if there is something specific about this plugin, but adding it to one of our repos tripled the test run times on circle CI. We have a couple other babel plugins that don't seem to have such a drastic effect.

Not sure if there is something that can be done about it, but we'll have to refrain from using this one for the moment.

**Comment by kutyel** [comment]
I'm sorry but there's literally nothing we can do to improve this, I don't know if migrating the plugin to Babel 7 would fix anything but I'll have a look just in case. Thanks for spotting the performance issue btw!!
