### ISSUE TITLE
Issue with webpack 4?

### ISSUE THREAD

**Issue by quantuminformation** [kutyel/babel-plugin-remove-test-ids#7]
Is this still maintained or is their a better npm module for webpack 4?

**Comment by kutyel** [comment]
What is the problem exactly? I could understand if this needed a new version for Babel 7 but I don't know what could be the issue with webpack 4, it is definitely maintained :)

**Comment by kutyel** [comment]
Closed until answered and a reproducible problem is provided.

**Comment by quantuminformation** [comment]
Was just wondering if it was compatible before trying it out.
